### ISSUE TITLE
Missing excel plugin

### ISSUE THREAD

**Issue by kimtoslo** [Borsdata-Sweden/ExcelPlugin#1]
The zipfile with the plugin is empty, its only an empty textfile called "Nytt textdokument.txt".

![picture](https://user-images.githubusercontent.com/63412223/78911313-71b33e00-7a86-11ea-9029-b5869270da4a.PNG)

**Comment by henrikbergstrom** [comment]
Hi,
The plugin is not release yet,
It's in deployment.
Tomorrow or next week its ready,

**Comment by kimtoslo** [comment]
Kul! Ser fram emot detta, riktigt imponerad över utvecklingen av börsdata rent generellt! 👍 Keep up the good work!
